aevea/commitsar

- go.mod
- internal/git/commit_text.go
- internal/git/commit_text_test.go
add functionality to get the text of a Commit
> feat: CommitText

- internal/text/check_message_title.go
- internal/text/check_message_title_test.go
- parses commit message to check conformity with conventional commits
> feat: CheckMessage

- internal/history/commits_on_branch.go
- internal/history/commits_on_branch_test.go
- CommitsOnBranch iterates through all references and returns commit hashes on that branch
> feat: commits on branch

- .drone.yml
- Dockerfile
- for CircleCI support ssh is needed
> fix: docker add ssh

- cmd/root_runner.go
Closes https://github.com/fallion/commitsar/issues/29
Any feedback much appreciated :)
> feat: list commits that have failed check

- .drone.yml
- .gitignore
- Makefile
- internal/history/commits_on_branch.go
- internal/history/commits_on_branch_test.go
- scripts/setup_commits_on_branch_test.sh
- create branch behind master
- update it by merging master into it
See `testdata/updateBranchMasterMerge` folder
Closes https://github.com/fallion/commitsar/issues/28
> fix: scan relevant history after merging master into branch

- .drone.yml
- README.md
- updates dockerhub build to new namespace
- updates badge in readme
> chore: updates following transfer

- .drone.yml
- scripts/setup_commits_on_branch_test.sh
- setup_commits_on_branch_test would overwrite local global git config assigning another user to the commit
> fix: Don't allow the test set up script to overwrite git config

- cmd/root_runner.go
> fix: no filtered commits not exiting

- Dockerfile
- cmd/root_runner.go
- adds Flags env var for Docker to allow verbose output to be turned on
- reads out commits in debug mode
> feat: add read-out of commits in debug

- cmd/root_runner.go
- fixes total number in successful flow as well
> feat: let user know amount of filtered commits

- scripts/publish_to_pages.sh
- www/go.sum
- caused by hugo mod get editing go.sum
> docs: fix git status check

- pkg/text/is_merge_commit.go
- pkg/text/is_merge_commit_test.go
- improves regex to cover /
- adds Merge master into renovate/docker-alpine-3.x style commit message compatibility
> fix: Kodiak style regex

- .drone.yml
- scripts/publish_to_pages.sh
- hugo mod get adds new tags to go.sum which breaks the runner
> docs: fix page publisher

- pkg/history/branch_diff_commits.go
- pkg/history/branch_diff_commits_test.go
- pkg/history/commits_on_branch_test.go
- introduces a wrapper for MergeBase
- finds all common ancestors between 2 branches
- improves testing by creating a new function that creates history for tests
> feat: BranchDiffCommits

- pkg/history/current_commit.go
- pkg/history/current_commit_test.go
- returns the commit object that HEAD is at
> feat: CurrentCommit

- pkg/history/commit.go
- pkg/history/commit_test.go
- Commit looks up and returns a commit object based on hash
> feat: Commit

- pkg/history/current_branch.go
- pkg/history/current_branch_test.go
- CurrentBranch returns the reference HEAD is at
> feat: CurrentBranch

- action.yml
- adds action.yml for use with Github actions
> feat: Github action

- Dockerfile
Seems this file is required for the action to run.
> fix(action): copy action.yml to dockerfile

- Dockerfile
- action.yml
- also reverts previous commiit
> fix(action): add missing required input field

- pkg/text/is_merge_commit.go
- pkg/text/is_merge_commit_test.go
- Github PR format was not covered by the regexes
Closes #92
> fix: certain merge commit styles fail test for merge commit

- .drone.yml
- .github/workflows/go.yml
- .github/workflows/release.yml
- removes duplicated steps from drone
> chore(ci): migrate to release-notary action

- cmd/root_runner.go
- pkg/text/format_failing_commits.go
- pkg/text/format_failing_commits_test.go
- commitsar will now report what is wrong with the commit
> feat: report errors

- pkg/history/branch_diff_commits.go
- branch_diff_commits will now report which branch failed
> chore: add error wrapping to branch_diff_commmits

- Dockerfile
- cmd/root_runner.go
- verbose output was turned on by default, it is no longer needed
> chore: turn off verbose output

- cmd/root_runner.go
- adds a message that will help user understand how to fix their commit
Closes #30
> feat: add help message

- cmd/root_runner.go
- internal/providers/find_compare_branch.go
- internal/providers/find_compare_branch_test.go
- tries to automate finding the upstream branch by using CI variables of different providers
> feat: find upstream branch

- internal/providers/find_compare_branch.go
- internal/providers/find_compare_branch_test.go
- adds checking for DRONE_TARGET_BRANCH which is the Drone variable for merge_request target branch
> feat(integrations): add Drone integration

- Dockerfile
- README.md
- cmd/identify_same_branch.go
- cmd/root.go
- cmd/root_runner.go
- go.mod
- go.sum
- main.go
- www/content/index.md
- www/go.mod
- www/go.sum
Update paths for the new naming
> chore: update paths

- cmd/cli/main.go
- internal/root_runner/commits_between_branches.go
- internal/root_runner/commits_between_hashes.go
- internal/root_runner/commits_between_hashes_test.go
- internal/root_runner/identify_same_branch.go
- internal/root_runner/root_runner.go
- internal/root_runner/root_runner_test.go
> refactor: rename runners -> root_runner

- Makefile
- cmd/cli/main.go
- internal/version_runner/version_runner.go
- internal/version_runner/version_runner_test.go
- adds command for displaying version and build-date of Commitsar
- adds new command building locally
- adjusts Makefile to provide git ref information for the build
Closes #168
> feat(CLI): add version command

- .gitignore
- Makefile
- cmd/cli/main.go
> fix: version info not propagated correctly during goreleaser build

- internal/root_runner/log_branch.go
- internal/root_runner/log_branch_test.go
- internal/root_runner/run.go
- internal/root_runner/run_test.go
> fix: log branch name when starting commitsar

- www/content/index.md
I really like the simplicity of your project and usage. It works well with my setup, so i thought I add a minimal version to your example page. If you have a different style I'm happy to adapt my commits :)
> Add GitLab CI example

- pkg/text/check_message_title.go
- pkg/text/check_message_title_test.go
> feat(checks): allow dashed and underscores in scope

- .commitsar.yaml
- .dockerignore
- config/commits.go
- config/commits_test.go
- config/config.go
- config/config_test.go
- config/testdata/.commitsar.yaml
- go.mod
- go.sum
- internal/root_runner/log_branch_test.go
- internal/root_runner/root_runner.go
- internal/root_runner/run.go
- internal/root_runner/run_test.go
- main.go
- www/docs/configuration/config-file.md
- www/sidebars.js
Using this file the usage of flags for common tasks can be dropped.
> Add support for configuration file

- internal/root_runner/run.go
- internal/root_runner/run_commits.go
The configuration option was set, it was however not functional.
> feat: allow commit checks to be skipped

- .commitsar.yaml
Needs fixing before next release but is currently blocking progress.
> fix(ci): temp disable PR check
