internal/git/commit_text.go
internal/git/commit_text_test.go

- CommitText would not propagate error higher
- fixes misleading test name

fix: CommitText not returning error

---

internal/text/check_message_title.go
internal/text/check_message_title_test.go

- fixes cases where `fix(stuff)(stuff): message` were possible
- fixes cases where double `!` was possible

fix(CheckMessage): fix edge cases in regex

---

internal/history/commits_on_branch.go
internal/history/commits_on_branch_test.go

- References will only list out branches etc., but not actual commits
- function has been expanded to use MergeBase
- after getting common ancestor it uses Log to iterate through commits between the head and common ancestor
- improved tests to reflect more commits on branch

fix(CommitsOnBranch): fixed CommitsOnBranch returning only 1 commit

---

.drone.yml
cmd/root.go
cmd/root_runner.go
internal/history/commits_on_branch.go

- uses RunE instead Run to gracefully handle errors
- adds missing returns of errors on commits not found
- adds debug print of references

improvement: error handling

---

cmd/root_runner.go
internal/history/commits_on_branch.go
internal/history/commits_on_branch_test.go

- fix: error on no commits found
- fix: pass head hash down instead of rebuilding from refrences
- ResolveRevision could not find reference built of branch name, however this is not required as we already have the hash of head

fix: missing commits and passing pipeline on 0 commits

---

Dockerfile

- not needed for simple tools
- removes ssh which was installed wrong

fix: remove user nobody

---

cmd/root_runner.go
pkg/text/check_message_title.go
pkg/text/message_title.go
pkg/text/message_title_test.go

- function to strip only the title from commit message
Closes #36

feat: MessageTitle

---

cmd/root_runner.go
pkg/text/format_failing_commits.go
pkg/text/format_failing_commits_test.go

- adds nicer formatting for failing commits
- allows user to see which messages failed

feat: format failing commits

---

cmd/root_runner.go
pkg/text/is_merge_commit.go
pkg/text/is_merge_commit_test.go

- runner will now filter out any merge commits

feat: filter out merge commits

---

pkg/history/open_git.go
pkg/history/open_git_test.go

BREAKING CHANGE: OpenGit should be used instead of Git
- OpenGit returns a Git struct which will be used to map all methods to from now on
- This pattern will be used going forward to hide reliance on using go-git directly

feat(history)!: Git struct

---

cmd/root_runner.go
pkg/history/branch_diff_commits.go
pkg/history/branch_diff_commits_test.go
pkg/history/commits_on_branch.go
pkg/history/commits_on_branch_test.go
pkg/history/latest_commit_on_branch.go
pkg/history/latest_commit_on_branch_test.go
scripts/setup_commits_on_branch_test.sh

BREAKING CHANGE: CommitsOnBranch is completely reworked to use a different method of getting commits. It no longer provides a diff and returns only Commits on branch
- Reworked CommitsOnBranch
- Reworked BranchDiffCommits to not use merge base anymore but to provide a diff of commits between branches
- Exposed LatestCommitsOnBranch
- Adjusted rootRunner to use new methods

fix!: Correctly detect commits on branch

---

pkg/history/commits_between.go
pkg/history/commits_between_test.go

- CommitsBetween iterates through commits from `git log` and returns them until it reaches a `to` stopping point

feat: CommitsBetween

---

pkg/history/commit_date.go

- Committer should always be the latest as it is the dare when the commit is actually made

fix: Use Committer date instead of Author

---

README.md
www/content/index.md

- removes false claim that the binary needs to be in same folder as git repository
- adds example usage with Github actions
Closes #93

docs: Improve readme

---

cmd/root_runner.go
pkg/text/check_message_title.go
pkg/text/check_message_title_test.go
pkg/text/commit.go
pkg/text/parse_commit.go
pkg/text/parse_commit_test.go

- adds ParseCommit functionality
- adds custom Commit struct
- adds levels of error to check_message_title

feat: ParseCommit and Error levels

---

pkg/text/check_message_title.go
pkg/text/check_message_title_test.go

- check_message_title will now warn when breaking change is missing a commit body
- check_message_title will now error when BC body does not start with BREAKING CHANGE:
Closes #34

feat: breaking change errors

---

pkg/history/commits_on_branch.go

- in situations where GIT_DEPTH is set CommitsOnBranch would fail and not return all commits it got

fix: CommitOnBranch failing when end of commits reached

---

Dockerfile

- FLAGS is currently not used, but it fails the build

fix(docker): remove FLAGS

---

internal/providers/find_compare_branch.go
internal/providers/find_compare_branch_test.go

- without origin go-git would not resolve the branch name

fix: prepend origin in compare branch name

---

cmd/root.go
cmd/root_runner.go
pkg/text/check_message_title.go
pkg/text/check_message_title_test.go

This mode makes sure that the category is one of the currently
defined categories in Angular's contributing guide.
{"build", "ci", "docs", "feat", "fix", "perf", "refactor", "style", "test"}
It's true by default, as it serves better most of the cases where
an opinionated style guide is used.
Closes #31

feat!: Add strict mode

---

README.md
cmd/commits_between_branches.go
cmd/commits_between_hashes.go
cmd/commits_between_hashes_test.go
cmd/root.go
cmd/root_runner.go
cmd/root_runner_test.go

- separates out commitsBetweenHashes and commitsBetweenBranches logic
- adds new argument for CLI
- adds new Flags section in README
- adds description for running commitsar with the argument for FROM...TO commit
References #165

feat: add from-to flags

---

internal/root_runner/commits_between_hashes.go
internal/root_runner/commits_between_hashes_test.go

By using the same order feature parity is kept.
References #165

fix: reverse order of from...to to to...from to reflect git log usage

---

cmd/cli/main.go

RootCmd requires a MinimumArgs attribute to be filled in order to expect args.
See: https://github.com/spf13/cobra#example
References #165

fix(cmd): to...from was broken since adding version command

---

cmd/cli/main.go
internal/root_runner/root_runner.go
internal/root_runner/root_runner_test.go

Allows for much nicer code with fewer if debug {}
Closes #88

refactor(logging): Use log.Logger for logging instead of debug flag

---

testdata/setup-test-repos.sh

Copied from Release Notary. Makes it much simpler to add new git test bundles

chore: simplify setup test repo creation script

---

internal/root_runner/root_runner.go
pkg/text/is_initial_commit.go
pkg/text/is_initial_commit_test.go

Currently it is impossible to run commitsar with Initial Commit messages which are common place in a lot of repositories

feat: skip initial commit messages

---

cmd/cli/main.go
internal/root_runner/root_runner.go
internal/root_runner/run.go
internal/root_runner/run_test.go

The arguments for RootRunner.Run kept getting bigger. This will consolidate it in one spot and allow for better defaults and checking.

refactor: use struct for RootRunner Run method

---

cmd/cli/main.go

Global variables were being mapped to main in main.go, but not actually used.

refactor: main global variables

---

README.md
internal/root_runner/commits_between_branches.go
internal/root_runner/commits_between_branches_test.go
internal/root_runner/run.go

This flag allows to opt into checking the entire upstream branch. 
This allows users to use it on whole repositories to check for any problematic commits.
Refs #187

feature: --all flag

---

pkg/text/check_message_title.go
pkg/text/check_message_title_test.go

BREAKING CHANGE: Commitsar will no longer fail if commit body is not present in a commit marked as a breaking change.

fix(conventional standard)!: breaking changes do not require body

---

CNAME

We no longer use Github pages, so this file is not needed.

chore: remove CNAME file

---

internal/dispatcher/dispatcher.go
internal/dispatcher/dispatcher_test.go
internal/dispatcher/handle_errors.go
internal/dispatcher/pipeline.go
internal/dispatcher/success_handler.go
internal/dispatcher/work.go

This package serves as a starting point to rebuild each part of root_runner into a pipeline allowing for more modularity going forward.

feat: introduce dispatcher package

---

config/commits.go
config/commits_test.go
internal/commitpipeline/pipeline.go
internal/commitpipeline/run.go
internal/root_runner/root_runner.go
internal/root_runner/run.go
main.go
pkg/text/check_required_scopes.go
pkg/text/check_required_scopes_test.go

hey @fallion, I've tried to keep those changes minimal and aligned with coding conventions - happy to make further adjustments if needed.
Some discussion items:
- `r` seems like a weak shorthand for `required-scopes`, but since it's required to be the single letter I didn't come up with anything better, wdyt?
- I decided to go with a single option being a list of required scopes. This addition is backward compatible. It could be done with multiple config values, fe. one enforcing scope and other listing allowed ones, but IMO single config makes more sense
- initially, I've added dynamic formatting of error (listing all required-scopes that did not match) in the check results table, but since that can break formatting in case of longer required-scopes lists - I've made a fallback to the …

feat: add required-scopes option for stricter scope validations

---

www/docusaurus.config.js

It was pointing to Docusaurus' otherwise.

fix(www): make GitHub link point to this repo

---

config/commits.go
config/commits_test.go
config/testdata/.commitsar.yaml
main.go
www/docs/configuration/config-file.md

The default is still `origin/master` as given by
github.com/aevea/integrations's FindCompareBranch,
but it is now possible to use
```yaml
commits:
upstreamBranch: origin/main
```
in your `.commitsar.yaml` config file to target
`origin/main` as upstream branch.
It does not quite fix the following related issue
as it proposed to have both `origin/master` and
`origin/main` as default upstream branches, but
it at least offers to configure the upstream
branch as a first step.
Related issue: https://github.com/aevea/commitsar/issues/317

feat(config): add commits.upstreamBranch option

---

internal/commitpipeline/run.go
pkg/text/is_revert_commit.go
pkg/text/is_revert_commit_test.go

Previously Revert commits would fail the pipeline as they were not considered conventional commit friendly.
This caused issues in multiple projects as commitsar checks would just be ignored.
Closes #434

feat: allow revert commits

---

internal/commitpipeline/run.go

Exit with success if all the commits to be checked have been filtered out
Closes #465

fix: do not fail if all commits have been filtered out

---

.goreleaser.yml

by default go env vars already have sane values that we shouldn't override; tools that rely on the value of GOOS or GOARCH to resolve the binary name need additional tweaking in our repo because of those overrides we set up

chore(goreleaser): remove archive string replacements

---

internal/commitpipeline/run.go

All commit hash is wrong `0000000000000000000000000000000000000000`
**fixed**

fix(commit): wrong hash commit in log

---

internal/prpipeline/run.go
internal/prpipeline/types.go
internal/root_runner/run.go

I think that this is only an internal name, so will not effect external use (in configs or...).
So correcting the spelling should not cause pain.

fix: correct the spelling of ConventionalStyle
